[parameters]
deliverymethod=StaticWeb
nos=CopyLocal
globalname=MOZ.MZF_EN.WIN.INSTALL.CLIENT_WIN.PLAT.REF.RR1001.A
pkgname=Mozilla Firefox Rapid Release
[responses]
submit_button=Install
servicename=IBM Standard Software Installer
restrictedgroups=geodis;toshiba;concentrix;GlobalFoundries
appowner=Erika Naomi Inazaki/Brazil/IBM
requirement=20360
workitem=43163
[first_contact]
[first_contact2]
logServer=issidb-test.boulder.ibm.com
logScript=/cgi-bin/weblog.sh
servername=w3-01.ibm.com
blueGroupServername=bluepages.ibm.com
nos=http
pkgnos=
remoteserverpath=/gsa/a01gsa/.projects/p1/aheweb01/projects/w3/data/download/standardsoftware/
httpRemoteServerPath=/download/standardsoftware
httpDirListMethod=cgi
httpCgiScriptName=/cgi-bin/download/standardsoftware/dirlist.pl
httpPortNumber=80
CheckPointRestartFlag=TRUE
MaxStageDays=180
InstallEZUpdate=TRUE
InstallDefergui=TRUE
UserAuthorization=TRUE
GlobalEntitlement=TRUE
GridClientAvailable=FALSE
IsamRegistrationAudit=TRUE
EZservername=w3-01.ibm.com
EZhttpRemoteServerPath=/download/standardsoftware
EZremoteserverpath=/gsa/a01gsa/.projects/p1/aheweb01/projects/w3/data/download/standardsoftware/
EZhttpPortNumber=80
WebServername=w3-01.ibm.com
WebHttpremoteserverpath=/download/standardsoftware
Webremoteserverpath=/gsa/a01gsa/.projects/p1/aheweb01/projects/w3/data/download/standardsoftware/
WebHttpportnumber=80
tstEZservername=ospdb.pok.ibm.com
tstEZhttpRemoteServerPath=/download/standardsoftware
tstEZremoteserverpath=/usr/local/etc/httpd/htdocs/content/download/standardsoftware
tstEZhttpPortNumber=80
maxlogfilesize=1000000
[targetos]
w2k=NONE
wxp=NONE
lnx=NONE
w73=NONE
w76=NONE
w13=ALL
w16=ALL
[version]
webprmpt=1.20
